import type { Farmstay } from "@/shared/types/farmstay";

/** Dữ liệu mẫu — sẽ thay bằng Sanity CMS ở Lệnh 40 */
export const FARMSTAYS: Farmstay[] = [
  {
    id: "1",
    slug: "doi-che-sunrise-moc-chau",
    name: "Đồi Chè Sunrise Mộc Châu",
    location: "Mộc Châu · Sơn La",
    province: "Sơn La",
    region: "north",
    tags: ["Đồi chè", "Cắm trại", "Hái chè"],
    price: 850000,
    rating: 4.9,
    reviewCount: 127,
    badges: ["verified"],
    emoji: "🌿",
    lat: 20.83,
    lng: 104.64,
  },
  {
    id: "2",
    slug: "ruong-bac-thang-heritage-farm",
    name: "Ruộng Bậc Thang Heritage Farm",
    location: "Mù Cang Chải · Yên Bái",
    province: "Yên Bái",
    region: "north",
    tags: ["Lúa nước", "Trekking", "Văn hoá Mông"],
    price: 1200000,
    rating: 4.8,
    reviewCount: 89,
    badges: ["verified"],
    emoji: "🌾",
    lat: 21.72,
    lng: 104.04,
  },
  {
    id: "3",
    slug: "vuon-ca-phe-robusta-kon-tum",
    name: "Vườn Cà Phê Robusta Kon Tum",
    location: "Đắk Hà · Kon Tum",
    province: "Kon Tum",
    region: "central",
    tags: ["Cà phê", "Tây Nguyên", "Chăn nuôi"],
    price: 680000,
    rating: 4.7,
    reviewCount: 64,
    badges: ["verified"],
    emoji: "☕",
    lat: 14.59,
    lng: 107.9,
  },
  {
    id: "4",
    slug: "vuon-trai-cay-mekong-delta",
    name: "Vườn Trái Cây Mekong Delta",
    location: "Cái Bè · Tiền Giang",
    province: "Tiền Giang",
    region: "south",
    tags: ["Trái cây", "Thuyền kênh", "Sông nước"],
    price: 550000,
    rating: 4.6,
    reviewCount: 43,
    badges: ["verified", "new"],
    emoji: "🌴",
    lat: 10.4,
    lng: 106.0,
  },
  {
    id: "5",
    slug: "lang-hoa-sa-dec-garden",
    name: "Làng Hoa Sa Đéc Garden",
    location: "Sa Đéc · Đồng Tháp",
    province: "Đồng Tháp",
    region: "south",
    tags: ["Hoa cây cảnh", "Chụp ảnh", "Workshop"],
    price: 720000,
    rating: 4.8,
    reviewCount: 71,
    badges: ["verified"],
    emoji: "🌸",
    lat: 10.29,
    lng: 105.79,
  },
  {
    id: "6",
    slug: "khu-sinh-thai-ru-linh",
    name: "Khu Sinh Thái Rú Lĩnh",
    location: "Khe Sanh · Quảng Trị",
    province: "Quảng Trị",
    region: "central",
    tags: ["200ha", "Sinh thái", "Trải nghiệm"],
    price: 1500000,
    rating: 5.0,
    reviewCount: 38,
    badges: ["verified", "featured"],
    emoji: "🌊",
    lat: 16.62,
    lng: 106.73,
  },
];
