import type { Farmstay } from "@/shared/types/farmstay";

/** Dữ liệu mẫu — sẽ thay bằng Sanity CMS khi kết nối */
export const FARMSTAYS: Farmstay[] = [
  // ── MIỀN BẮC ──
  {
    id: "1",
    slug: "doi-che-sunrise-moc-chau",
    name: "Đồi Chè Sunrise Mộc Châu",
    location: "Mộc Châu · Sơn La",
    province: "Sơn La",
    region: "north",
    tags: ["Đồi chè", "Cắm trại", "Hái chè"],
    price: 850000,
    rating: 4.9,
    reviewCount: 127,
    badges: ["verified"],
    emoji: "🌿",
    lat: 20.83,
    lng: 104.64,
  },
  {
    id: "2",
    slug: "ruong-bac-thang-heritage-farm",
    name: "Ruộng Bậc Thang Heritage Farm",
    location: "Mù Cang Chải · Yên Bái",
    province: "Yên Bái",
    region: "north",
    tags: ["Lúa nước", "Trekking", "Văn hoá Mông"],
    price: 1200000,
    rating: 4.8,
    reviewCount: 89,
    badges: ["verified"],
    emoji: "🌾",
    lat: 21.72,
    lng: 104.04,
  },
  {
    id: "7",
    slug: "trang-trai-hoa-tam-giac-mach-ha-giang",
    name: "Trang Trại Hoa Tam Giác Mạch Hà Giang",
    location: "Đồng Văn · Hà Giang",
    province: "Hà Giang",
    region: "north",
    tags: ["Tam giác mạch", "Cao nguyên đá", "Văn hoá Lô Lô"],
    price: 980000,
    rating: 4.9,
    reviewCount: 156,
    badges: ["verified", "featured"],
    emoji: "🌸",
    lat: 23.27,
    lng: 105.36,
  },
  {
    id: "8",
    slug: "vuon-dao-bac-ha-farm",
    name: "Vườn Đào Bắc Hà Farm",
    location: "Bắc Hà · Lào Cai",
    province: "Lào Cai",
    region: "north",
    tags: ["Vườn đào", "Chợ phiên", "Văn hoá H'Mông"],
    price: 750000,
    rating: 4.7,
    reviewCount: 93,
    badges: ["verified"],
    emoji: "🍑",
    lat: 22.54,
    lng: 104.29,
  },
  {
    id: "9",
    slug: "nha-san-co-tho-binh-lieu",
    name: "Nhà Sàn Cổ Thổ Bình Liêu",
    location: "Bình Liêu · Quảng Ninh",
    province: "Quảng Ninh",
    region: "north",
    tags: ["Nhà sàn", "Thác nước", "Rừng trúc"],
    price: 620000,
    rating: 4.6,
    reviewCount: 48,
    badges: ["verified", "new"],
    emoji: "🏕️",
    lat: 21.79,
    lng: 107.66,
  },

  // ── MIỀN TRUNG ──
  {
    id: "3",
    slug: "vuon-ca-phe-robusta-kon-tum",
    name: "Vườn Cà Phê Robusta Kon Tum",
    location: "Đắk Hà · Kon Tum",
    province: "Kon Tum",
    region: "central",
    tags: ["Cà phê", "Tây Nguyên", "Chăn nuôi"],
    price: 680000,
    rating: 4.7,
    reviewCount: 64,
    badges: ["verified"],
    emoji: "☕",
    lat: 14.59,
    lng: 107.9,
  },
  {
    id: "6",
    slug: "khu-sinh-thai-ru-linh",
    name: "Khu Sinh Thái Rú Lĩnh",
    location: "Khe Sanh · Quảng Trị",
    province: "Quảng Trị",
    region: "central",
    tags: ["200ha", "Sinh thái", "Trải nghiệm"],
    price: 1500000,
    rating: 5.0,
    reviewCount: 38,
    badges: ["verified", "featured"],
    emoji: "🌊",
    lat: 16.62,
    lng: 106.73,
  },
  {
    id: "10",
    slug: "trang-trai-dau-tam-bao-loc",
    name: "Trang Trại Dâu Tằm Bảo Lộc",
    location: "Bảo Lộc · Lâm Đồng",
    province: "Lâm Đồng",
    region: "central",
    tags: ["Dâu tằm", "Trà B'Lao", "Ươm tơ"],
    price: 890000,
    rating: 4.8,
    reviewCount: 112,
    badges: ["verified"],
    emoji: "🌱",
    lat: 11.54,
    lng: 107.81,
  },
  {
    id: "11",
    slug: "vung-ca-phe-arabica-da-lat",
    name: "Vùng Cà Phê Arabica Đà Lạt",
    location: "Lạc Dương · Đà Lạt",
    province: "Lâm Đồng",
    region: "central",
    tags: ["Arabica", "Cà phê đặc sản", "Khí hậu mát"],
    price: 1100000,
    rating: 4.9,
    reviewCount: 203,
    badges: ["verified", "featured"],
    emoji: "☕",
    lat: 12.02,
    lng: 108.55,
  },
  {
    id: "12",
    slug: "lang-luoi-cham-thuan-an",
    name: "Làng Lưới Chài Thuận An",
    location: "Thuận An · Thừa Thiên Huế",
    province: "Thừa Thiên Huế",
    region: "central",
    tags: ["Biển đầm phá", "Chài lưới", "Ẩm thực Huế"],
    price: 550000,
    rating: 4.5,
    reviewCount: 57,
    badges: ["verified", "new"],
    emoji: "🎣",
    lat: 16.42,
    lng: 107.72,
  },

  // ── MIỀN NAM ──
  {
    id: "4",
    slug: "vuon-trai-cay-mekong-delta",
    name: "Vườn Trái Cây Mekong Delta",
    location: "Cái Bè · Tiền Giang",
    province: "Tiền Giang",
    region: "south",
    tags: ["Trái cây", "Thuyền kênh", "Sông nước"],
    price: 550000,
    rating: 4.6,
    reviewCount: 43,
    badges: ["verified", "new"],
    emoji: "🌴",
    lat: 10.4,
    lng: 106.0,
  },
  {
    id: "5",
    slug: "lang-hoa-sa-dec-garden",
    name: "Làng Hoa Sa Đéc Garden",
    location: "Sa Đéc · Đồng Tháp",
    province: "Đồng Tháp",
    region: "south",
    tags: ["Hoa cây cảnh", "Chụp ảnh", "Workshop"],
    price: 720000,
    rating: 4.8,
    reviewCount: 71,
    badges: ["verified"],
    emoji: "🌸",
    lat: 10.29,
    lng: 105.79,
  },
  {
    id: "13",
    slug: "trang-trai-sau-rieng-king-can-tho",
    name: "Trang Trại Sầu Riêng King Cần Thơ",
    location: "Phong Điền · Cần Thơ",
    province: "Cần Thơ",
    region: "south",
    tags: ["Sầu riêng", "Miệt vườn", "Ghe xuồng"],
    price: 480000,
    rating: 4.6,
    reviewCount: 84,
    badges: ["verified"],
    emoji: "🍈",
    lat: 10.13,
    lng: 105.75,
  },
  {
    id: "14",
    slug: "vuon-hieu-mam-ca-mau",
    name: "Vườn Hiệu Mắm Cà Mau",
    location: "Năm Căn · Cà Mau",
    province: "Cà Mau",
    region: "south",
    tags: ["Rừng đước", "Bắt cua", "Mắm đặc sản"],
    price: 620000,
    rating: 4.7,
    reviewCount: 66,
    badges: ["verified"],
    emoji: "🦀",
    lat: 8.98,
    lng: 105.0,
  },
  {
    id: "15",
    slug: "eco-farm-binh-phuoc-dieu-hoa",
    name: "Eco Farm Điều Hoà Bình Phước",
    location: "Đồng Phú · Bình Phước",
    province: "Bình Phước",
    region: "south",
    tags: ["Điều", "Hồ tiêu", "Sinh thái"],
    price: 790000,
    rating: 4.5,
    reviewCount: 29,
    badges: ["new"],
    emoji: "🌰",
    lat: 11.53,
    lng: 106.9,
  },
];
